Repository eisuke-nakanishi-4243121/janken, pull requests merged in 2024-11, with the labels that each got.

#8 じゃんけんコントロール #4
  janken.py
Labels: 緊急, 作業中

#5 ユーザーからの入力 #3
  janken.py
Labels: 緊急, 作業中

#6 ランダム変数#2
  janken.py
Labels: 緊急

#7 D勝敗判定の作成 #1
  janken.py
Labels: 緊急, 完了

#9 Update janken.py
  janken.py
Labels: 緊急, 作業中, 衝突
